#Ce fichier contiens la config de base du serveur---
Main:
    theme:
        couleurs:
            main-color-bg: '#e6e6e6'
            secondary-color-bg: '#43b9f4'
            base-color: '#d6d6d6'
            main-color: '#3805f0'
            active-color: '#c772e4'
            lightest: '#000000'
            darkest: '#3f3f3f'
            bonus1: '#009ffd'
            bonus2: '#06d6a0'
            txtnav: '#ffffff'
        informations:
            img1: https://images.sky-dream.fr/upload-img-site/tokens-16000.png
            titre1: Achetez mes tokens!
            desc1: Achetez mes beaux tokens....
            couleurtitre1: '#fbe527'
            couleurdesc1: '#878786'
            couleurback1: '#c4c4c4'
            img2: 'https://images.sky-dream.fr/upload-img-site/Espada%20Madera.png'
            titre2: Achète un kevin
            desc2: Il est bo mon kevin....
            couleurtitre2: '#41c9cb'
            couleurdesc2: '#878786'
            couleurback2: '#c4c4c4'
            img3: https://images.sky-dream.fr/upload-img-site/vote.png
            titre3: Oui nous avons des votes
            desc3: Vote et gagne des choses cool (askip)
            couleurtitre3: '#695d6f'
            couleurdesc3: '#878786'
            couleurback3: '#c4c4c4'
        police: "'Poppins', sans-serif;"
        logo: 'https://images.sky-dream.fr/upload-img-gfx/SKYDREAM%20TRASNPARENT.png'
        logo-l: 350px
        logo-h: 240px
        discord-id: "685431569472946197"
        discord-invitation: https://discord.gg/2dwkBYP5Gr
Pied:
    couleurbg: '#383838'
    about: sqfqsffsfqsfqsfq
