#Ce fichier contiens la config de base du serveur---
Main:
    theme:
        couleurs:
            main-color-bg: '#ffffff'
            secondary-color-bg: '#3a50a1'
            base-color: '#c2c2c2'
            main-color: '#4ad1e3'
            active-color: '#c772e4'
            lightest: '#000000'
            darkest: '#3f3f3f'
            bonus1: '#009ffd'
            bonus2: '#06d6a0'
            txtnav: '#ffffff'
        informations:
            img1: https://images.sky-dream.fr/upload-img-site/tokens-16000.png
            titre1: Achetez mes tokens!
            desc1: Achetez mes beaux tokens....
            couleurtitre1: '#4a4a4a'
            couleurdesc1: '#6a4848'
            img2: 'https://images.sky-dream.fr/upload-img-site/Espada%20Madera.png'
            titre2: Achète un kevin
            desc2: Il est bo mon kevin....
            couleurtitre2: '#000000'
            couleurdesc2: '#6c7df9'
            img3: https://images.sky-dream.fr/upload-img-site/vote.png
            titre3: Oui nous avons des votes
            desc3: Vote et gagne des choses cool (askip)
            couleurtitre3: '#695d6f'
            couleurdesc3: '#2f985c'
        police: "'Poppins', sans-serif;"
        bg: >
            https://images.sky-dream.fr/upload-img-gfx/9cf5b64d6cd2963ef96eabb4b2c1cbe6.jpg
        logo: 'https://images.sky-dream.fr/upload-img-gfx/SKYDREAM%20TRASNPARENT.png'
        logo-l: 350px
        logo-h: 240px
        discord-id: "685431569472946197"
        discord-invitation: https://discord.gg/2dwkBYP5Gr
Pied:
    about: Bienvenue sur mon site !fssffsfs22559
    social:
        - 
            icon: "<i class='fab fa-discord'></i>"
            link: https://www.discord.com/
            message: Rejoignez-nous sur Discord !
        - 
            icon: "<i class='fab fa-youtube'></i>"
            link: https://www.youtube.com/
            message: Rejoignez-nous sur Youtube !
        - 
            icon: "<i class='fab fa-twitter'></i>"
            link: https://www.twitter.com/
            message: Rejoignez-nous sur Twitter !
